# Generated by Django 5.0.7 on 2024-07-28 21:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentResponse",
            fields=[
                (
                    "user_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="Guest", max_length=100)),
                ("EXT1", models.IntegerField(default=0)),
                ("EXT2", models.IntegerField(default=0)),
                ("EXT3", models.IntegerField(default=0)),
                ("EXT4", models.IntegerField(default=0)),
                ("EXT5", models.IntegerField(default=0)),
                ("EXT6", models.IntegerField(default=0)),
                ("EXT7", models.IntegerField(default=0)),
                ("EXT8", models.IntegerField(default=0)),
                ("EXT9", models.IntegerField(default=0)),
                ("EXT10", models.IntegerField(default=0)),
                ("EST1", models.IntegerField(default=0)),
                ("EST2", models.IntegerField(default=0)),
                ("EST3", models.IntegerField(default=0)),
                ("EST4", models.IntegerField(default=0)),
                ("EST5", models.IntegerField(default=0)),
                ("EST6", models.IntegerField(default=0)),
                ("EST7", models.IntegerField(default=0)),
                ("EST8", models.IntegerField(default=0)),
                ("EST9", models.IntegerField(default=0)),
                ("EST10", models.IntegerField(default=0)),
                ("AGR1", models.IntegerField(default=0)),
                ("AGR2", models.IntegerField(default=0)),
                ("AGR3", models.IntegerField(default=0)),
                ("AGR4", models.IntegerField(default=0)),
                ("AGR5", models.IntegerField(default=0)),
                ("AGR6", models.IntegerField(default=0)),
                ("AGR7", models.IntegerField(default=0)),
                ("AGR8", models.IntegerField(default=0)),
                ("AGR9", models.IntegerField(default=0)),
                ("AGR10", models.IntegerField(default=0)),
                ("CSN1", models.IntegerField(default=0)),
                ("CSN2", models.IntegerField(default=0)),
                ("CSN3", models.IntegerField(default=0)),
                ("CSN4", models.IntegerField(default=0)),
                ("CSN5", models.IntegerField(default=0)),
                ("CSN6", models.IntegerField(default=0)),
                ("CSN7", models.IntegerField(default=0)),
                ("CSN8", models.IntegerField(default=0)),
                ("CSN9", models.IntegerField(default=0)),
                ("CSN10", models.IntegerField(default=0)),
                ("OPN1", models.IntegerField(default=0)),
                ("OPN2", models.IntegerField(default=0)),
                ("OPN3", models.IntegerField(default=0)),
                ("OPN4", models.IntegerField(default=0)),
                ("OPN5", models.IntegerField(default=0)),
                ("OPN6", models.IntegerField(default=0)),
                ("OPN7", models.IntegerField(default=0)),
                ("OPN8", models.IntegerField(default=0)),
                ("OPN9", models.IntegerField(default=0)),
                ("OPN10", models.IntegerField(default=0)),
            ],
        ),
    ]
